/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthCheckRouteImport } from './routes/auth-check'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListRouteImport } from './routes/list'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PreLovedRouteImport } from './routes/pre-loved'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRentalsRouteImport } from './routes/_authenticated/rentals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminProductImagesRouteImport } from './routes/admin/product-images'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPurchasesRouteImport } from './routes/admin/purchases'
import { Route as AdminRefundsRouteImport } from './routes/admin/refunds'
import { Route as AdminRentalsRouteImport } from './routes/admin/rentals'
import { Route as AdminReturnsRouteImport } from './routes/admin/returns'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSellersRouteImport } from './routes/admin/sellers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesCategorySlugRouteImport } from './routes/categories/$categorySlug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as SellerAnalyticsRouteImport } from './routes/seller/analytics'
import { Route as SellerBecomeASellerRouteImport } from './routes/seller/become-a-seller'
import { Route as SellerEarningsRouteImport } from './routes/seller/earnings'
import { Route as SellerMessagesRouteImport } from './routes/seller/messages'
import { Route as SellerOrdersRouteImport } from './routes/seller/orders'
import { Route as SellerProductsRouteImport } from './routes/seller/products'
import { Route as SellerRentalsRouteImport } from './routes/seller/rentals'
import { Route as SellerReviewsRouteImport } from './routes/seller/reviews'
import { Route as SellerSettingsRouteImport } from './routes/seller/settings'
import { Route as SellerWalletRouteImport } from './routes/seller/wallet'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedProfileActivityRouteImport } from './routes/_authenticated/profile.activity'
import { Route as AuthenticatedProfileOrdersRouteImport } from './routes/_authenticated/profile.orders'
import { Route as AuthenticatedProfileRentalsRouteImport } from './routes/_authenticated/profile.rentals'
import { Route as AuthenticatedProfileWishlistRouteImport } from './routes/_authenticated/profile.wishlist'
import { Route as AuthenticatedRentalsRentalIdRouteImport } from './routes/_authenticated/rentals.$rentalId'
import { Route as AdminReviewsSellersRouteImport } from './routes/admin/reviews.sellers'
import { Route as SellerProductsNewRouteImport } from './routes/seller/products.new'
import { Route as SellerProductsProductIdEditRouteImport } from './routes/seller/products.$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckRoute = AuthCheckRouteImport.update({
  id: '/auth-check',
  path: '/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PreLovedRoute = PreLovedRouteImport.update({
  id: '/pre-loved',
  path: '/pre-loved',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRentalsRoute = AuthenticatedRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductImagesRoute = AdminProductImagesRouteImport.update({
  id: '/product-images',
  path: '/product-images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalsRoute = AdminRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategorySlugRoute = CategoriesCategorySlugRouteImport.update({
  id: '/categories/$categorySlug',
  path: '/categories/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/seller/',
  path: '/seller/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/seller/analytics',
  path: '/seller/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerBecomeASellerRoute = SellerBecomeASellerRouteImport.update({
  id: '/seller/become-a-seller',
  path: '/seller/become-a-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerEarningsRoute = SellerEarningsRouteImport.update({
  id: '/seller/earnings',
  path: '/seller/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerMessagesRoute = SellerMessagesRouteImport.update({
  id: '/seller/messages',
  path: '/seller/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/seller/products',
  path: '/seller/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRentalsRoute = SellerRentalsRouteImport.update({
  id: '/seller/rentals',
  path: '/seller/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/seller/reviews',
  path: '/seller/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/seller/settings',
  path: '/seller/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerWalletRoute = SellerWalletRouteImport.update({
  id: '/seller/wallet',
  path: '/seller/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedProfileActivityRoute =
  AuthenticatedProfileActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileOrdersRoute =
  AuthenticatedProfileOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileRentalsRoute =
  AuthenticatedProfileRentalsRouteImport.update({
    id: '/rentals',
    path: '/rentals',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileWishlistRoute =
  AuthenticatedProfileWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedRentalsRentalIdRoute =
  AuthenticatedRentalsRentalIdRouteImport.update({
    id: '/$rentalId',
    path: '/$rentalId',
    getParentRoute: () => AuthenticatedRentalsRoute,
  } as any)
const AdminReviewsSellersRoute = AdminReviewsSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminReviewsRoute,
} as any)
const SellerProductsNewRoute = SellerProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SellerProductsRoute,
} as any)
const SellerProductsProductIdEditRoute =
  SellerProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => SellerProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/rentals': typeof AuthenticatedRentalsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-images': typeof AdminProductImagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/become-a-seller': typeof SellerBecomeASellerRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRouteWithChildren
  '/seller/rentals': typeof SellerRentalsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/profile/activity': typeof AuthenticatedProfileActivityRoute
  '/profile/orders': typeof AuthenticatedProfileOrdersRoute
  '/profile/rentals': typeof AuthenticatedProfileRentalsRoute
  '/profile/wishlist': typeof AuthenticatedProfileWishlistRoute
  '/rentals/$rentalId': typeof AuthenticatedRentalsRentalIdRoute
  '/admin/reviews/sellers': typeof AdminReviewsSellersRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/products/$productId/edit': typeof SellerProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/rentals': typeof AuthenticatedRentalsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-images': typeof AdminProductImagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/become-a-seller': typeof SellerBecomeASellerRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRouteWithChildren
  '/seller/rentals': typeof SellerRentalsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/seller': typeof SellerIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/profile/activity': typeof AuthenticatedProfileActivityRoute
  '/profile/orders': typeof AuthenticatedProfileOrdersRoute
  '/profile/rentals': typeof AuthenticatedProfileRentalsRoute
  '/profile/wishlist': typeof AuthenticatedProfileWishlistRoute
  '/rentals/$rentalId': typeof AuthenticatedRentalsRentalIdRoute
  '/admin/reviews/sellers': typeof AdminReviewsSellersRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/products/$productId/edit': typeof SellerProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/rentals': typeof AuthenticatedRentalsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-images': typeof AdminProductImagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/become-a-seller': typeof SellerBecomeASellerRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRouteWithChildren
  '/seller/rentals': typeof SellerRentalsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/profile/activity': typeof AuthenticatedProfileActivityRoute
  '/_authenticated/profile/orders': typeof AuthenticatedProfileOrdersRoute
  '/_authenticated/profile/rentals': typeof AuthenticatedProfileRentalsRoute
  '/_authenticated/profile/wishlist': typeof AuthenticatedProfileWishlistRoute
  '/_authenticated/rentals/$rentalId': typeof AuthenticatedRentalsRentalIdRoute
  '/admin/reviews/sellers': typeof AdminReviewsSellersRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/products/$productId/edit': typeof SellerProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-check'
    | '/browse'
    | '/checkout'
    | '/how-it-works'
    | '/list'
    | '/payment'
    | '/pre-loved'
    | '/login'
    | '/register'
    | '/cart'
    | '/dashboard'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/rentals'
    | '/settings'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-images'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/refunds'
    | '/admin/rentals'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/users'
    | '/categories/$categorySlug'
    | '/product/$slug'
    | '/seller/$id'
    | '/seller/analytics'
    | '/seller/become-a-seller'
    | '/seller/earnings'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/rentals'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/wallet'
    | '/admin/'
    | '/categories/'
    | '/seller/'
    | '/orders/$orderId'
    | '/profile/activity'
    | '/profile/orders'
    | '/profile/rentals'
    | '/profile/wishlist'
    | '/rentals/$rentalId'
    | '/admin/reviews/sellers'
    | '/seller/products/new'
    | '/seller/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-check'
    | '/browse'
    | '/checkout'
    | '/how-it-works'
    | '/list'
    | '/payment'
    | '/pre-loved'
    | '/login'
    | '/register'
    | '/cart'
    | '/dashboard'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/rentals'
    | '/settings'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-images'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/refunds'
    | '/admin/rentals'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/users'
    | '/categories/$categorySlug'
    | '/product/$slug'
    | '/seller/$id'
    | '/seller/analytics'
    | '/seller/become-a-seller'
    | '/seller/earnings'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/rentals'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/wallet'
    | '/admin'
    | '/categories'
    | '/seller'
    | '/orders/$orderId'
    | '/profile/activity'
    | '/profile/orders'
    | '/profile/rentals'
    | '/profile/wishlist'
    | '/rentals/$rentalId'
    | '/admin/reviews/sellers'
    | '/seller/products/new'
    | '/seller/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/admin'
    | '/auth-check'
    | '/browse'
    | '/checkout'
    | '/how-it-works'
    | '/list'
    | '/payment'
    | '/pre-loved'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/cart'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/rentals'
    | '/_authenticated/settings'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-images'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/refunds'
    | '/admin/rentals'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/users'
    | '/categories/$categorySlug'
    | '/product/$slug'
    | '/seller/$id'
    | '/seller/analytics'
    | '/seller/become-a-seller'
    | '/seller/earnings'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/rentals'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/wallet'
    | '/admin/'
    | '/categories/'
    | '/seller/'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/profile/activity'
    | '/_authenticated/profile/orders'
    | '/_authenticated/profile/rentals'
    | '/_authenticated/profile/wishlist'
    | '/_authenticated/rentals/$rentalId'
    | '/admin/reviews/sellers'
    | '/seller/products/new'
    | '/seller/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthCheckRoute: typeof AuthCheckRoute
  BrowseRoute: typeof BrowseRoute
  CheckoutRoute: typeof CheckoutRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListRoute: typeof ListRoute
  PaymentRoute: typeof PaymentRoute
  PreLovedRoute: typeof PreLovedRoute
  CategoriesCategorySlugRoute: typeof CategoriesCategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  SellerIdRoute: typeof SellerIdRoute
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerBecomeASellerRoute: typeof SellerBecomeASellerRoute
  SellerEarningsRoute: typeof SellerEarningsRoute
  SellerMessagesRoute: typeof SellerMessagesRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRouteWithChildren
  SellerRentalsRoute: typeof SellerRentalsRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerWalletRoute: typeof SellerWalletRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-check': {
      id: '/auth-check'
      path: '/auth-check'
      fullPath: '/auth-check'
      preLoaderRoute: typeof AuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-loved': {
      id: '/pre-loved'
      path: '/pre-loved'
      fullPath: '/pre-loved'
      preLoaderRoute: typeof PreLovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rentals': {
      id: '/_authenticated/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof AuthenticatedRentalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-images': {
      id: '/admin/product-images'
      path: '/product-images'
      fullPath: '/admin/product-images'
      preLoaderRoute: typeof AdminProductImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rentals': {
      id: '/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug': {
      id: '/categories/$categorySlug'
      path: '/categories/$categorySlug'
      fullPath: '/categories/$categorySlug'
      preLoaderRoute: typeof CategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/seller'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/seller/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/become-a-seller': {
      id: '/seller/become-a-seller'
      path: '/seller/become-a-seller'
      fullPath: '/seller/become-a-seller'
      preLoaderRoute: typeof SellerBecomeASellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/earnings': {
      id: '/seller/earnings'
      path: '/seller/earnings'
      fullPath: '/seller/earnings'
      preLoaderRoute: typeof SellerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/messages': {
      id: '/seller/messages'
      path: '/seller/messages'
      fullPath: '/seller/messages'
      preLoaderRoute: typeof SellerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/seller/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/rentals': {
      id: '/seller/rentals'
      path: '/seller/rentals'
      fullPath: '/seller/rentals'
      preLoaderRoute: typeof SellerRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/seller/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/seller/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/wallet': {
      id: '/seller/wallet'
      path: '/seller/wallet'
      fullPath: '/seller/wallet'
      preLoaderRoute: typeof SellerWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/profile/activity': {
      id: '/_authenticated/profile/activity'
      path: '/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof AuthenticatedProfileActivityRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/orders': {
      id: '/_authenticated/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof AuthenticatedProfileOrdersRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/rentals': {
      id: '/_authenticated/profile/rentals'
      path: '/rentals'
      fullPath: '/profile/rentals'
      preLoaderRoute: typeof AuthenticatedProfileRentalsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/wishlist': {
      id: '/_authenticated/profile/wishlist'
      path: '/wishlist'
      fullPath: '/profile/wishlist'
      preLoaderRoute: typeof AuthenticatedProfileWishlistRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/rentals/$rentalId': {
      id: '/_authenticated/rentals/$rentalId'
      path: '/$rentalId'
      fullPath: '/rentals/$rentalId'
      preLoaderRoute: typeof AuthenticatedRentalsRentalIdRouteImport
      parentRoute: typeof AuthenticatedRentalsRoute
    }
    '/admin/reviews/sellers': {
      id: '/admin/reviews/sellers'
      path: '/sellers'
      fullPath: '/admin/reviews/sellers'
      preLoaderRoute: typeof AdminReviewsSellersRouteImport
      parentRoute: typeof AdminReviewsRoute
    }
    '/seller/products/new': {
      id: '/seller/products/new'
      path: '/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof SellerProductsNewRouteImport
      parentRoute: typeof SellerProductsRoute
    }
    '/seller/products/$productId/edit': {
      id: '/seller/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/seller/products/$productId/edit'
      preLoaderRoute: typeof SellerProductsProductIdEditRouteImport
      parentRoute: typeof SellerProductsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileActivityRoute: typeof AuthenticatedProfileActivityRoute
  AuthenticatedProfileOrdersRoute: typeof AuthenticatedProfileOrdersRoute
  AuthenticatedProfileRentalsRoute: typeof AuthenticatedProfileRentalsRoute
  AuthenticatedProfileWishlistRoute: typeof AuthenticatedProfileWishlistRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileActivityRoute: AuthenticatedProfileActivityRoute,
  AuthenticatedProfileOrdersRoute: AuthenticatedProfileOrdersRoute,
  AuthenticatedProfileRentalsRoute: AuthenticatedProfileRentalsRoute,
  AuthenticatedProfileWishlistRoute: AuthenticatedProfileWishlistRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRentalsRouteChildren {
  AuthenticatedRentalsRentalIdRoute: typeof AuthenticatedRentalsRentalIdRoute
}

const AuthenticatedRentalsRouteChildren: AuthenticatedRentalsRouteChildren = {
  AuthenticatedRentalsRentalIdRoute: AuthenticatedRentalsRentalIdRoute,
}

const AuthenticatedRentalsRouteWithChildren =
  AuthenticatedRentalsRoute._addFileChildren(AuthenticatedRentalsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedRentalsRoute: typeof AuthenticatedRentalsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedRentalsRoute: AuthenticatedRentalsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminReviewsRouteChildren {
  AdminReviewsSellersRoute: typeof AdminReviewsSellersRoute
}

const AdminReviewsRouteChildren: AdminReviewsRouteChildren = {
  AdminReviewsSellersRoute: AdminReviewsSellersRoute,
}

const AdminReviewsRouteWithChildren = AdminReviewsRoute._addFileChildren(
  AdminReviewsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductImagesRoute: typeof AdminProductImagesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminRentalsRoute: typeof AdminRentalsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminReviewsRoute: typeof AdminReviewsRouteWithChildren
  AdminSellersRoute: typeof AdminSellersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductImagesRoute: AdminProductImagesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminRentalsRoute: AdminRentalsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminReviewsRoute: AdminReviewsRouteWithChildren,
  AdminSellersRoute: AdminSellersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerProductsRouteChildren {
  SellerProductsNewRoute: typeof SellerProductsNewRoute
  SellerProductsProductIdEditRoute: typeof SellerProductsProductIdEditRoute
}

const SellerProductsRouteChildren: SellerProductsRouteChildren = {
  SellerProductsNewRoute: SellerProductsNewRoute,
  SellerProductsProductIdEditRoute: SellerProductsProductIdEditRoute,
}

const SellerProductsRouteWithChildren = SellerProductsRoute._addFileChildren(
  SellerProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthCheckRoute: AuthCheckRoute,
  BrowseRoute: BrowseRoute,
  CheckoutRoute: CheckoutRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListRoute: ListRoute,
  PaymentRoute: PaymentRoute,
  PreLovedRoute: PreLovedRoute,
  CategoriesCategorySlugRoute: CategoriesCategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  SellerIdRoute: SellerIdRoute,
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerBecomeASellerRoute: SellerBecomeASellerRoute,
  SellerEarningsRoute: SellerEarningsRoute,
  SellerMessagesRoute: SellerMessagesRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRouteWithChildren,
  SellerRentalsRoute: SellerRentalsRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerWalletRoute: SellerWalletRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  SellerIndexRoute: SellerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
