/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthCheckRouteImport } from './routes/auth-check'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListRouteImport } from './routes/list'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PreLovedRouteImport } from './routes/pre-loved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminProductImagesRouteImport } from './routes/admin/product-images'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPurchasesRouteImport } from './routes/admin/purchases'
import { Route as AdminRefundsRouteImport } from './routes/admin/refunds'
import { Route as AdminRentalsRouteImport } from './routes/admin/rentals'
import { Route as AdminReturnsRouteImport } from './routes/admin/returns'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSellersRouteImport } from './routes/admin/sellers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesCategorySlugRouteImport } from './routes/categories/$categorySlug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardBecomeASellerRouteImport } from './routes/dashboard/become-a-seller'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard/earnings'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardRentalsRouteImport } from './routes/dashboard/rentals'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardWalletRouteImport } from './routes/dashboard/wallet'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ProfileActivityRouteImport } from './routes/profile.activity'
import { Route as ProfileOrdersRouteImport } from './routes/profile.orders'
import { Route as ProfileRentalsRouteImport } from './routes/profile.rentals'
import { Route as ProfileWishlistRouteImport } from './routes/profile.wishlist'
import { Route as RentalsRentalIdRouteImport } from './routes/rentals.$rentalId'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as AdminReviewsSellersRouteImport } from './routes/admin/reviews.sellers'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products.new'
import { Route as DashboardProductsProductIdEditRouteImport } from './routes/dashboard/products.$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckRoute = AuthCheckRouteImport.update({
  id: '/auth-check',
  path: '/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PreLovedRoute = PreLovedRouteImport.update({
  id: '/pre-loved',
  path: '/pre-loved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductImagesRoute = AdminProductImagesRouteImport.update({
  id: '/product-images',
  path: '/product-images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalsRoute = AdminRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategorySlugRoute = CategoriesCategorySlugRouteImport.update({
  id: '/categories/$categorySlug',
  path: '/categories/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBecomeASellerRoute = DashboardBecomeASellerRouteImport.update({
  id: '/dashboard/become-a-seller',
  path: '/dashboard/become-a-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/dashboard/earnings',
  path: '/dashboard/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/dashboard/messages',
  path: '/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/dashboard/orders',
  path: '/dashboard/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/dashboard/products',
  path: '/dashboard/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRentalsRoute = DashboardRentalsRouteImport.update({
  id: '/dashboard/rentals',
  path: '/dashboard/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/dashboard/wallet',
  path: '/dashboard/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileActivityRoute = ProfileActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileOrdersRoute = ProfileOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileRentalsRoute = ProfileRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileWishlistRoute = ProfileWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ProfileRoute,
} as any)
const RentalsRentalIdRoute = RentalsRentalIdRouteImport.update({
  id: '/$rentalId',
  path: '/$rentalId',
  getParentRoute: () => RentalsRoute,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsSellersRoute = AdminReviewsSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminReviewsRoute,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProductsRoute,
} as any)
const DashboardProductsProductIdEditRoute =
  DashboardProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => DashboardProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/profile': typeof ProfileRouteWithChildren
  '/rentals': typeof RentalsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-images': typeof AdminProductImagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/become-a-seller': typeof DashboardBecomeASellerRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/rentals': typeof ProfileRentalsRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/reviews/sellers': typeof AdminReviewsSellersRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/profile': typeof ProfileRouteWithChildren
  '/rentals': typeof RentalsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-images': typeof AdminProductImagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/become-a-seller': typeof DashboardBecomeASellerRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/rentals': typeof ProfileRentalsRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/reviews/sellers': typeof AdminReviewsSellersRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/profile': typeof ProfileRouteWithChildren
  '/rentals': typeof RentalsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-images': typeof AdminProductImagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRouteWithChildren
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/become-a-seller': typeof DashboardBecomeASellerRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/rentals': typeof ProfileRentalsRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/reviews/sellers': typeof AdminReviewsSellersRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-check'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/how-it-works'
    | '/list'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payment'
    | '/pre-loved'
    | '/profile'
    | '/rentals'
    | '/login'
    | '/register'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-images'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/refunds'
    | '/admin/rentals'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/users'
    | '/categories/$categorySlug'
    | '/dashboard/analytics'
    | '/dashboard/become-a-seller'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/rentals'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/profile/activity'
    | '/profile/orders'
    | '/profile/rentals'
    | '/profile/wishlist'
    | '/rentals/$rentalId'
    | '/seller/$id'
    | '/admin/'
    | '/categories/'
    | '/dashboard/'
    | '/admin/reviews/sellers'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-check'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/how-it-works'
    | '/list'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payment'
    | '/pre-loved'
    | '/profile'
    | '/rentals'
    | '/login'
    | '/register'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-images'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/refunds'
    | '/admin/rentals'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/users'
    | '/categories/$categorySlug'
    | '/dashboard/analytics'
    | '/dashboard/become-a-seller'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/rentals'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/profile/activity'
    | '/profile/orders'
    | '/profile/rentals'
    | '/profile/wishlist'
    | '/rentals/$rentalId'
    | '/seller/$id'
    | '/admin'
    | '/categories'
    | '/dashboard'
    | '/admin/reviews/sellers'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/auth-check'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/how-it-works'
    | '/list'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payment'
    | '/pre-loved'
    | '/profile'
    | '/rentals'
    | '/_auth/login'
    | '/_auth/register'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-images'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/refunds'
    | '/admin/rentals'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/users'
    | '/categories/$categorySlug'
    | '/dashboard/analytics'
    | '/dashboard/become-a-seller'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/rentals'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/profile/activity'
    | '/profile/orders'
    | '/profile/rentals'
    | '/profile/wishlist'
    | '/rentals/$rentalId'
    | '/seller/$id'
    | '/admin/'
    | '/categories/'
    | '/dashboard/'
    | '/admin/reviews/sellers'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthCheckRoute: typeof AuthCheckRoute
  BrowseRoute: typeof BrowseRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListRoute: typeof ListRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  PreLovedRoute: typeof PreLovedRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RentalsRoute: typeof RentalsRouteWithChildren
  CategoriesCategorySlugRoute: typeof CategoriesCategorySlugRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBecomeASellerRoute: typeof DashboardBecomeASellerRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
  DashboardRentalsRoute: typeof DashboardRentalsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  ProductSlugRoute: typeof ProductSlugRoute
  SellerIdRoute: typeof SellerIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-check': {
      id: '/auth-check'
      path: '/auth-check'
      fullPath: '/auth-check'
      preLoaderRoute: typeof AuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-loved': {
      id: '/pre-loved'
      path: '/pre-loved'
      fullPath: '/pre-loved'
      preLoaderRoute: typeof PreLovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-images': {
      id: '/admin/product-images'
      path: '/product-images'
      fullPath: '/admin/product-images'
      preLoaderRoute: typeof AdminProductImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rentals': {
      id: '/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug': {
      id: '/categories/$categorySlug'
      path: '/categories/$categorySlug'
      fullPath: '/categories/$categorySlug'
      preLoaderRoute: typeof CategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/become-a-seller': {
      id: '/dashboard/become-a-seller'
      path: '/dashboard/become-a-seller'
      fullPath: '/dashboard/become-a-seller'
      preLoaderRoute: typeof DashboardBecomeASellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/dashboard/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/dashboard/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rentals': {
      id: '/dashboard/rentals'
      path: '/dashboard/rentals'
      fullPath: '/dashboard/rentals'
      preLoaderRoute: typeof DashboardRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/activity': {
      id: '/profile/activity'
      path: '/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof ProfileActivityRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/orders': {
      id: '/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof ProfileOrdersRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/rentals': {
      id: '/profile/rentals'
      path: '/rentals'
      fullPath: '/profile/rentals'
      preLoaderRoute: typeof ProfileRentalsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/wishlist': {
      id: '/profile/wishlist'
      path: '/wishlist'
      fullPath: '/profile/wishlist'
      preLoaderRoute: typeof ProfileWishlistRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/rentals/$rentalId': {
      id: '/rentals/$rentalId'
      path: '/$rentalId'
      fullPath: '/rentals/$rentalId'
      preLoaderRoute: typeof RentalsRentalIdRouteImport
      parentRoute: typeof RentalsRoute
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews/sellers': {
      id: '/admin/reviews/sellers'
      path: '/sellers'
      fullPath: '/admin/reviews/sellers'
      preLoaderRoute: typeof AdminReviewsSellersRouteImport
      parentRoute: typeof AdminReviewsRoute
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/dashboard/products/$productId/edit': {
      id: '/dashboard/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/dashboard/products/$productId/edit'
      preLoaderRoute: typeof DashboardProductsProductIdEditRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminReviewsRouteChildren {
  AdminReviewsSellersRoute: typeof AdminReviewsSellersRoute
}

const AdminReviewsRouteChildren: AdminReviewsRouteChildren = {
  AdminReviewsSellersRoute: AdminReviewsSellersRoute,
}

const AdminReviewsRouteWithChildren = AdminReviewsRoute._addFileChildren(
  AdminReviewsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductImagesRoute: typeof AdminProductImagesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminRentalsRoute: typeof AdminRentalsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminReviewsRoute: typeof AdminReviewsRouteWithChildren
  AdminSellersRoute: typeof AdminSellersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductImagesRoute: AdminProductImagesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminRentalsRoute: AdminRentalsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminReviewsRoute: AdminReviewsRouteWithChildren,
  AdminSellersRoute: AdminSellersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProfileRouteChildren {
  ProfileActivityRoute: typeof ProfileActivityRoute
  ProfileOrdersRoute: typeof ProfileOrdersRoute
  ProfileRentalsRoute: typeof ProfileRentalsRoute
  ProfileWishlistRoute: typeof ProfileWishlistRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileActivityRoute: ProfileActivityRoute,
  ProfileOrdersRoute: ProfileOrdersRoute,
  ProfileRentalsRoute: ProfileRentalsRoute,
  ProfileWishlistRoute: ProfileWishlistRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface RentalsRouteChildren {
  RentalsRentalIdRoute: typeof RentalsRentalIdRoute
}

const RentalsRouteChildren: RentalsRouteChildren = {
  RentalsRentalIdRoute: RentalsRentalIdRoute,
}

const RentalsRouteWithChildren =
  RentalsRoute._addFileChildren(RentalsRouteChildren)

interface DashboardProductsRouteChildren {
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardProductsProductIdEditRoute: typeof DashboardProductsProductIdEditRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardProductsProductIdEditRoute: DashboardProductsProductIdEditRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthCheckRoute: AuthCheckRoute,
  BrowseRoute: BrowseRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListRoute: ListRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PaymentRoute: PaymentRoute,
  PreLovedRoute: PreLovedRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RentalsRoute: RentalsRouteWithChildren,
  CategoriesCategorySlugRoute: CategoriesCategorySlugRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBecomeASellerRoute: DashboardBecomeASellerRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
  DashboardRentalsRoute: DashboardRentalsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  ProductSlugRoute: ProductSlugRoute,
  SellerIdRoute: SellerIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
