/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthCheckRouteImport } from './routes/auth-check'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListRouteImport } from './routes/list'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PreLovedRouteImport } from './routes/pre-loved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesCategorySlugRouteImport } from './routes/categories/$categorySlug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardBecomeASellerRouteImport } from './routes/dashboard/become-a-seller'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard/earnings'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardRentalsRouteImport } from './routes/dashboard/rentals'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as RentalsRentalIdRouteImport } from './routes/rentals.$rentalId'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products.new'
import { Route as DashboardProductsProductIdEditRouteImport } from './routes/dashboard/products./$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckRoute = AuthCheckRouteImport.update({
  id: '/auth-check',
  path: '/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PreLovedRoute = PreLovedRouteImport.update({
  id: '/pre-loved',
  path: '/pre-loved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategorySlugRoute = CategoriesCategorySlugRouteImport.update({
  id: '/categories/$categorySlug',
  path: '/categories/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBecomeASellerRoute = DashboardBecomeASellerRouteImport.update({
  id: '/dashboard/become-a-seller',
  path: '/dashboard/become-a-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/dashboard/earnings',
  path: '/dashboard/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/dashboard/messages',
  path: '/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/dashboard/orders',
  path: '/dashboard/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/dashboard/products',
  path: '/dashboard/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRentalsRoute = DashboardRentalsRouteImport.update({
  id: '/dashboard/rentals',
  path: '/dashboard/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRentalIdRoute = RentalsRentalIdRouteImport.update({
  id: '/$rentalId',
  path: '/$rentalId',
  getParentRoute: () => RentalsRoute,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProductsRoute,
} as any)
const DashboardProductsProductIdEditRoute =
  DashboardProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => DashboardProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/profile': typeof ProfileRoute
  '/rentals': typeof RentalsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/become-a-seller': typeof DashboardBecomeASellerRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/profile': typeof ProfileRoute
  '/rentals': typeof RentalsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/become-a-seller': typeof DashboardBecomeASellerRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth-check': typeof AuthCheckRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/pre-loved': typeof PreLovedRoute
  '/profile': typeof ProfileRoute
  '/rentals': typeof RentalsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/become-a-seller': typeof DashboardBecomeASellerRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-check'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/how-it-works'
    | '/list'
    | '/orders'
    | '/payment'
    | '/pre-loved'
    | '/profile'
    | '/rentals'
    | '/login'
    | '/register'
    | '/categories/$categorySlug'
    | '/dashboard/analytics'
    | '/dashboard/become-a-seller'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/rentals'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/rentals/$rentalId'
    | '/seller/$id'
    | '/categories/'
    | '/dashboard/'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth-check'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/how-it-works'
    | '/list'
    | '/orders'
    | '/payment'
    | '/pre-loved'
    | '/profile'
    | '/rentals'
    | '/login'
    | '/register'
    | '/categories/$categorySlug'
    | '/dashboard/analytics'
    | '/dashboard/become-a-seller'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/rentals'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/rentals/$rentalId'
    | '/seller/$id'
    | '/categories'
    | '/dashboard'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/auth-check'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/how-it-works'
    | '/list'
    | '/orders'
    | '/payment'
    | '/pre-loved'
    | '/profile'
    | '/rentals'
    | '/_auth/login'
    | '/_auth/register'
    | '/categories/$categorySlug'
    | '/dashboard/analytics'
    | '/dashboard/become-a-seller'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/rentals'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/rentals/$rentalId'
    | '/seller/$id'
    | '/categories/'
    | '/dashboard/'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthCheckRoute: typeof AuthCheckRoute
  BrowseRoute: typeof BrowseRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListRoute: typeof ListRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  PreLovedRoute: typeof PreLovedRoute
  ProfileRoute: typeof ProfileRoute
  RentalsRoute: typeof RentalsRouteWithChildren
  CategoriesCategorySlugRoute: typeof CategoriesCategorySlugRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBecomeASellerRoute: typeof DashboardBecomeASellerRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
  DashboardRentalsRoute: typeof DashboardRentalsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  SellerIdRoute: typeof SellerIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-check': {
      id: '/auth-check'
      path: '/auth-check'
      fullPath: '/auth-check'
      preLoaderRoute: typeof AuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-loved': {
      id: '/pre-loved'
      path: '/pre-loved'
      fullPath: '/pre-loved'
      preLoaderRoute: typeof PreLovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug': {
      id: '/categories/$categorySlug'
      path: '/categories/$categorySlug'
      fullPath: '/categories/$categorySlug'
      preLoaderRoute: typeof CategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/become-a-seller': {
      id: '/dashboard/become-a-seller'
      path: '/dashboard/become-a-seller'
      fullPath: '/dashboard/become-a-seller'
      preLoaderRoute: typeof DashboardBecomeASellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/dashboard/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/dashboard/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rentals': {
      id: '/dashboard/rentals'
      path: '/dashboard/rentals'
      fullPath: '/dashboard/rentals'
      preLoaderRoute: typeof DashboardRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/$rentalId': {
      id: '/rentals/$rentalId'
      path: '/$rentalId'
      fullPath: '/rentals/$rentalId'
      preLoaderRoute: typeof RentalsRentalIdRouteImport
      parentRoute: typeof RentalsRoute
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/dashboard/products/$productId/edit': {
      id: '/dashboard/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/dashboard/products/$productId/edit'
      preLoaderRoute: typeof DashboardProductsProductIdEditRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface RentalsRouteChildren {
  RentalsRentalIdRoute: typeof RentalsRentalIdRoute
}

const RentalsRouteChildren: RentalsRouteChildren = {
  RentalsRentalIdRoute: RentalsRentalIdRoute,
}

const RentalsRouteWithChildren =
  RentalsRoute._addFileChildren(RentalsRouteChildren)

interface DashboardProductsRouteChildren {
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardProductsProductIdEditRoute: typeof DashboardProductsProductIdEditRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardProductsProductIdEditRoute: DashboardProductsProductIdEditRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthCheckRoute: AuthCheckRoute,
  BrowseRoute: BrowseRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListRoute: ListRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PaymentRoute: PaymentRoute,
  PreLovedRoute: PreLovedRoute,
  ProfileRoute: ProfileRoute,
  RentalsRoute: RentalsRouteWithChildren,
  CategoriesCategorySlugRoute: CategoriesCategorySlugRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBecomeASellerRoute: DashboardBecomeASellerRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
  DashboardRentalsRoute: DashboardRentalsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  ProductSlugRoute: ProductSlugRoute,
  SellerIdRoute: SellerIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
